---
- name: install and deploy portfolio
  hosts: webservers

  tasks:
  - name: create web server directory
    file:
      path: /var/www/html
      state: directory
      mode: 0755

  - name: deploy code from gitlab
    git:
      repo: "{{ git_repo }}"
      accept_hostkey: yes
      dest: /var/www/html/

  - name: install apache2
    apt:
      name: apache2
      state: latest
      update_cache: yes

  - name: start apache2
    service:
      name: apache2
      state: started
      enabled: yes
