---
- name: install and deploy portfolio
  hosts: webservers

  tasks:
  - name: create web server directory
    file:
      path: /var/www/html
      state: directory
      mode: 0755

  - name: deploy code from git
    git:
      repo: "{{ git_repo }}"
      accept_hostkey: yes
      dest: /var/www/html/

  - name: install apache2
    apt:
      name: apache2
      state: latest
      update_cache: yes
    notify: restart apache2

  handlers:
  - name: restart apache2
    service:
      name: apache2
      state: restarted
